version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: forsit-ecommerce
      POSTGRES_USER: forsit-ecommerce-user
      POSTGRES_PASSWORD: forsit-ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forsit-ecommerce-admin-api
    restart: always
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh scripts/init.sh

volumes:
  postgres_data:
